### ISSUE TITLE
freezes/crashes game

### ISSUE THREAD

**Issue by RaySylvan** [Ceppy82/MoveScriptChanger#3]
[_latest.log](https://github.com/Ceppy82/MoveScriptChanger/files/5585214/_latest.log)
upon choosing a gamemode, beat saber stops responding and will not load. Removal of movie script dll fixed issue.

**Comment by Ceppy82** [comment]
MoveScriptChanger.dll is in "BeatSaberDir\Plugins"?

No sign of MoveScriptChanger in your log. ^^

**Comment by RaySylvan** [comment]
sorry about that. I pasted the log from after I removed it MSC. Here's a more recent one with it re-installed (same issue as before).
[_latest.log](https://github.com/Ceppy82/MoveScriptChanger/files/5585366/_latest.log)

**Comment by Ceppy82** [comment]
Ok, could be related to the Oculus app. 
I have the same problem with my Oculus version.

I am trying to find the exact cause.

Thank you for reporting!

**Comment by Ceppy82** [comment]
Found the mistake, it was my fault. Just add another Movescript to the Randompool for a hotfix.

the fixed version is also available immediately.

Sorry
